# Main application settings
app:
  # Time to wait between checking for new posts, in seconds
  wait_time_seconds: 300
  # Path to the state file, which stores the ID of the last processed post
  state_file: "state.yaml"
  # Name of the session file for the Telegram user account
  session_name: "user_session"

# A list of VK to Telegram/Boosty bindings
bindings:
- vk:
    # Short name or ID of the community wall to monitor
    domain: "somegroup"
    # Number of posts to fetch in each check
    post_count: 10
    # Source of posts: "wall" for public posts, "donut" for VK Donut posts
    post_source: "wall"
  telegram:
    # List of your channel usernames (e.g., @channel_name) or numeric IDs
    channel_ids:
    - "@firstid"
    - "@secondid"
  boosty:
    # Your Boosty blog name (the part after boosty.to/ in the URL)
    blog_name: "my_boosty_blog"

- vk:
    # Short name or ID of the community wall to monitor
    domain: "somesecondgroup"
    # Number of posts to fetch in each check
    post_count: 10
    # Source of posts: "wall" for public posts, "donut" for VK Donut posts
    post_source: "donut"
  telegram:
    # List of your channel usernames (e.g., @channel_name) or numeric IDs
    channel_ids:
    - "@secondid1"
    - "@secondid2"

# Video downloader settings
downloader:
  # Browser to use for importing cookies (e.g., chrome, firefox, edge)
  browser: "firefox"
  # Directory to save downloaded videos
  output_path: "downloads"
  # Time to wait after restarting the browser to refresh cookies, in seconds
  browser_restart_wait_seconds: 30
  # Settings for retrying failed downloads
  retries:
    # Number of retries for a failed download
    count: 3
    # Initial delay between retries, in seconds (increases exponentially)
    delay_seconds: 10 # yt-dlp options for downloading
  yt_dlp_opts:
    format: "best[height<=1080]/bestvideo[height<=1080]+bestaudio"
    # Skip unavailable fragments    
    skip_unavailable_fragments: false
    # Number of retries for each fragment
    fragment_retries: 50
    # Total number of retries for the download
    retries: 50
    # External downloader to use
    external_downloader:
      default: "aria2c"
      dash: "native"
      m3u8: "native"
    merge_output_format: mp4
    concurrent_fragments: 8
    # Arguments for the external downloader
    external_downloader_args:
      aria2c:
      # - "-x5"
      # - "-s5"
      - "-k1M"
